# Numpy Library

In [2]:
# import numpy library

import numpy as np

In [3]:
# creating a numpy array

np_array = np.array([1, 2, 3, 4, 5])

print(np_array)

[1 2 3 4 5]


In [4]:
print(type(np_array))

# numpy.ndarray --> numpy n dimensional array

<class 'numpy.ndarray'>


In [5]:
# add 2 to every element in an array --> [1, 2, 3, 4, 5] --> [3, 4, 5, 6, 7]

print(np_array)

np_array2 = np_array + 2

print(np_array2)

[1 2 3 4 5]
[3 4 5 6 7]


In [6]:
# Masking in numpy

data = np.array([1, 9, 8, 4, 5, 2, 7, 3, 12])

print(data)

[ 1  9  8  4  5  2  7  3 12]


In [8]:
# let's say I want only elements from this above data where the element is greater than 5

# creating a mask for this condidion

mask = data > 5

print(mask)

[False  True  True False False False  True False  True]


In [9]:
# use and apply the mask to data

filtered_data = data[mask]

print(filtered_data)

[ 9  8  7 12]


# Real World Case Study --> Finding NPS of a company

In [ ]:
# What is NPS? -->> Net Promoter Score

# How likely are you going to recommend this product to one of your friends? --> Rate between 1 to 10

# To understand the feedback of the user of the product

# Ex: How likely are you going to recommend any workshop to one of your friends? --> Rate betwween 1 to 10 -->

# Promoters --> rating 9 and 10 --> 60 --> people who will promote your service to others

# Demoters --> rating between 1 to 6 --> 20 --> people who will say bad things about your service

# Passive --> rating between 7 to 8 --> 20 --> people who are neither happy nor sad with the product

# nps --> ((promoters - demoters)/ total_feedback received )*100

# nps --> ((60-20)/100)*100 = 40

# higher the nps --> better the product || Lower the nps --> bad is the product

In [ ]:
# Dataset link: https://drive.google.com/drive/u/0/home

# Find nps of this product

In [ ]:
# Step 1: Download the dataset and load it in a numpy array

# downloaded the dataset in the data tab in google collab notebook/ jupyter notebook

In [18]:
# loading the dataset into a numpy array

scores = np.loadtxt('survey (1).txt')

In [19]:
# print the dataset

print(scores)

[ 7. 10.  5. ...  5.  9. 10.]


In [20]:
# check the dataset dimensions

print(scores.ndim)

1


In [21]:
print(len(scores))

# how many reviews are there in this feedback txt file

1167


In [22]:
# find the promoters

# who are promoters? --> people who have given more than 8 rating (> 8)

promoter_mask = scores > 8

print(promoter_mask)

[False  True False ... False  True  True]


In [23]:
# apply the mask

promoters = scores[promoter_mask]

print(promoters)

[10.  9.  9.  9.  9.  9. 10.  9.  9. 10.  9.  9.  9.  9.  9.  9.  9. 10.
 10.  9. 10.  9. 10.  9.  9. 10. 10.  9. 10.  9. 10. 10. 10.  9.  9. 10.
 10. 10.  9. 10.  9. 10.  9.  9.  9. 10.  9.  9.  9.  9.  9.  9. 10.  9.
  9.  9. 10.  9. 10.  9.  9.  9.  9.  9. 10. 10.  9. 10.  9.  9. 10.  9.
  9. 10.  9.  9.  9.  9.  9.  9.  9.  9.  9.  9.  9. 10.  9.  9.  9.  9.
  9.  9.  9.  9. 10.  9.  9.  9.  9.  9. 10. 10.  9. 10. 10. 10. 10.  9.
 10.  9.  9.  9.  9.  9.  9.  9. 10.  9. 10.  9. 10.  9. 10. 10. 10.  9.
  9. 10. 10.  9.  9.  9.  9. 10.  9.  9.  9.  9. 10. 10.  9.  9.  9. 10.
  9.  9.  9.  9.  9. 10.  9.  9.  9. 10.  9. 10. 10.  9.  9.  9.  9. 10.
  9. 10.  9.  9.  9.  9. 10.  9. 10.  9.  9.  9.  9.  9.  9.  9.  9.  9.
  9.  9. 10. 10.  9.  9.  9. 10.  9. 10. 10. 10. 10. 10.  9.  9.  9.  9.
 10. 10. 10.  9.  9. 10.  9. 10. 10. 10. 10.  9. 10. 10.  9. 10.  9.  9.
  9.  9. 10.  9. 10.  9. 10.  9.  9.  9.  9. 10.  9.  9.  9.  9.  9. 10.
  9. 10. 10.  9. 10. 10. 10.  9.  9.  9.  9.  9.  9

In [24]:
# number of promoters

num_promoters = len(promoters)

print(num_promoters)

609


In [25]:
# find the demoters from the dataset

# who are demoters --> people who give rating < 7 (1 to 6 -> 6 including) or <=6

demoter_mask = scores < 7

print(demoter_mask)

[False False  True ...  True False False]


In [26]:
# apply the mask

demoters = scores[demoter_mask]

print(demoters)

[5. 4. 4. 5. 1. 5. 5. 1. 4. 5. 4. 4. 4. 5. 1. 4. 1. 4. 1. 5. 5. 1. 1. 4.
 1. 5. 4. 1. 1. 4. 1. 5. 1. 4. 4. 1. 1. 1. 1. 1. 1. 1. 4. 1. 1. 5. 5. 5.
 4. 4. 1. 4. 1. 4. 1. 5. 1. 1. 5. 4. 4. 4. 4. 1. 4. 5. 4. 4. 1. 1. 5. 5.
 1. 5. 1. 5. 5. 4. 5. 4. 1. 1. 1. 1. 4. 1. 4. 4. 5. 4. 1. 1. 1. 1. 5. 4.
 5. 5. 4. 1. 5. 1. 4. 4. 1. 1. 1. 4. 4. 5. 5. 4. 5. 5. 5. 1. 4. 1. 5. 5.
 1. 5. 1. 1. 5. 5. 4. 4. 1. 4. 4. 4. 1. 1. 4. 4. 4. 5. 5. 1. 1. 4. 1. 4.
 1. 4. 1. 4. 1. 4. 1. 5. 4. 4. 5. 1. 4. 5. 5. 5. 1. 5. 4. 1. 1. 5. 5. 5.
 4. 5. 4. 4. 1. 4. 4. 4. 4. 5. 1. 5. 5. 1. 4. 4. 5. 1. 1. 4. 5. 5. 5. 1.
 4. 5. 5. 4. 1. 5. 5. 5. 1. 1. 5. 5. 1. 1. 1. 4. 5. 5. 4. 4. 4. 5. 1. 4.
 1. 4. 5. 4. 5. 5. 1. 5. 1. 5. 5. 1. 4. 5. 5. 4. 1. 5. 1. 4. 1. 4. 1. 1.
 1. 1. 1. 1. 4. 1. 5. 4. 5. 1. 5. 1. 5. 4. 4. 4. 4. 5. 5. 1. 4. 1. 5. 5.
 1. 4. 1. 1. 4. 4. 4. 4. 1. 4. 1. 1. 4. 1. 5. 4. 1. 1. 5. 4. 5. 4. 4. 4.
 1. 5. 5. 1. 4. 5. 4. 4. 4. 1. 4. 1. 4. 4. 4. 5. 1. 1. 1. 4. 5. 5. 1. 5.
 4. 5. 5. 4. 1. 1. 5. 5. 5. 1. 4. 5. 4. 5. 5. 5. 1.

In [27]:
# number of demoters

num_demoters = len(demoters)

print(num_demoters)

332


In [28]:
total_reviews = len(scores)

print(total_reviews)

1167


In [29]:
# calculate the Nps

Nps = ((num_promoters - num_demoters)/total_reviews)*100

print(Nps)

23.736075407026565
